# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: https://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run_with_env.cmd"

  matrix:
     - PYTHON: "C:\\Python27_32"
       PYTHON_VERSION: "2.7.14"
       PYTHON_ARCH: "32"

     - PYTHON: "C:\\Python27_64"
       PYTHON_VERSION: "2.7.14"
       PYTHON_ARCH: "64"

     - PYTHON: "C:\\Python34_32"
       PYTHON_VERSION: "3.4.4"
       PYTHON_ARCH: "32"

     - PYTHON: "C:\\Python34_64"
       PYTHON_VERSION: "3.4.4"
       PYTHON_ARCH: "64"

     - PYTHON: "C:\\Python35_32"
       PYTHON_VERSION: "3.5.4"
       PYTHON_ARCH: "32"

     - PYTHON: "C:\\Python35_64"
       PYTHON_VERSION: "3.5.4"
       PYTHON_ARCH: "64"

     - PYTHON: "C:\\Python36_32"
       PYTHON_VERSION: "3.6"
       PYTHON_ARCH: "32"

     - PYTHON: "C:\\Python36_64"
       PYTHON_VERSION: "3.6"
       PYTHON_ARCH: "64"

install:
  # Install Python (from the official .msi of https://python.org) and pip when
  # not already installed.
  - "powershell ./ci/appveyor/install.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Install the build and runtime dependencies of the project.
  - "%CMD_IN_ENV% pip install -v six nose pytest pytest-cov coverage"

  # Install the generated wheel package to test it
  - "python setup.py install"


# Not a .NET project, we build scikit-image in the install step instead
build: false

test_script:

  # Run unit tests with nose
  - "python run_tests.py"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
